spring.application.name=QPSS

spring.datasource.url=jdbc:mariadb://localhost:3306/qpss
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql



spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

qpss.storage.question-banks=storage/question-banks
